#!/bin/bash

path=/var/www/colbyolson.com/media/images/background.jpg

image=$(
    curl -s https://twitter.com/FFD8FFDB | \
    grep "Embedded image permalink"      | \
    head -n1                             | \
    cut -d'"' -f2
)

curl -s -o $path $image
