#!/bin/bash

image=$(
    curl -s https://twitter.com/FFD8FFDB | \
    grep "Embedded image permalink"      | \
    head -n1                             | \
    cut -d'"' -f2
)

curl -s -o /var/www/blog/media/images/background.jpg $image
