#!/bin/bash

set -o errexit

path=$BLOG_PATH/public/media/images/background.jpg

image=$(
    curl -s https://twitter.com/FFD8FFDB | \
    grep "data-image-url"                | \
    head -n1                             | \
    cut -d'"' -f2
)

curl -s -o $path $image
