#!/bin/bash

set -o errexit

cd $BLOG_PATH

mkdir -p tmp pages public

rm -f tmp/*.html
rm -f pages/index.md

cross='<div class="cross">&#x271E;</div>'

posts=$(ls -t posts/*.md)

for p in $posts
do
    cat  $p     >> pages/index.md
    echo $cross >> pages/index.md
done

files=$(find drafts pages posts -name "*.md")

for f in $files
do
    multimarkdown $f -o tmp/$(echo $(basename $f) | cut -d. -f1).html
done

for f in tmp/*.html
do
    file="public/$(basename $f)"
 
    > $file
 
    cat lib/header.html >> $file
    cat $f              >> $file
    cat lib/footer.html >> $file
done
