#!/bin/bash

[ ! -d ./tmp ] && mkdir ./tmp
[ ! -d ./pages ] && mkdir ./pages
[ ! -d ./public ] && mkdir ./public

ls -t ./posts/*.md | xargs cat > ./pages/index.md

files=$(find ./pages ./posts -name "*.md")

for f in $files;
do
    multimarkdown $f -o ./tmp/$(echo $(basename $f) | cut -d. -f1).html
done

for f in ./tmp/*.html; 
do
    file="./public/$(basename $f)"
 
    > $file
 
    cat ./lib/header.html >> $file
    cat $f                >> $file
    cat ./lib/footer.html >> $file
done
