#!/bin/bash

set -o errexit

case $@ in
    *.md)
        file=$@
        ;;
    *)
        file=${@}.md
        ;;
esac

file=${file// /-}
link=${file::-3}

cd $BLOG_PATH

cat > drafts/$file <<EOL
# [$link](/$link)
EOL
